//
//  DailySummaryResultCard.swift
//  ADHD LifeOS
//

import SwiftUI

/// The result half of the Daily Executive Summary card: the generated sections, the failure
/// state, and the shared bits both need. Split from `DailySummaryView` so neither file carries
/// the whole screen — the composed view stays readable and both clear SwiftLint's file and
/// type-body limits.
struct DailySummaryResultCard: View {
    let generated: GeneratedDailySummary
    /// `nil` disables the copy control — the service owns whether there is anything to copy.
    let copyText: String?

    @State private var didCopy = false

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            header
            DailySummaryBulletSection(
                title: "Dopamine Wins", systemImage: "trophy.fill",
                items: generated.content.dopamineWins
            )
            DailySummaryParagraphSection(
                title: "Reflections", systemImage: "quote.bubble.fill",
                text: generated.content.journalReflections
            )
            DailySummaryParagraphSection(
                title: "Focus & Stamina", systemImage: "bolt.fill",
                text: generated.content.focusStaminaInsight
            )
            DailySummaryBulletSection(
                title: "Tomorrow's Kickstart", systemImage: "sunrise.fill",
                items: generated.content.gentleTomorrowKickstart
            )
        }
        .bentoCard()
        .overlay(
            RoundedRectangle(cornerRadius: 16, style: .continuous)
                .strokeBorder(Color.accentColor.opacity(0.2), lineWidth: 2)
        )
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: 8) {
                Image(systemName: "sparkles")
                    .font(.caption.weight(.bold))
                    .foregroundStyle(Color(.systemBackground))
                    .frame(width: 24, height: 24)
                    .background(.tint, in: Circle())
                Text("Daily Highlight")
                    .sectionLabel()
                    .foregroundStyle(.tint)
                Spacer(minLength: 0)
                copyButton
            }
            Text(generated.content.headline)
                .font(.title3.bold())
                .fixedSize(horizontal: false, vertical: true)
            provenance
        }
    }

    /// Always shown: a locally synthesized summary must never be mistaken for a model's, and a
    /// summary generated hours ago must never read as current.
    private var provenance: some View {
        Text(provenanceText)
            .font(.caption2.monospaced())
            .foregroundStyle(.secondary)
            .accessibilityLabel(
                "Generated by \(generated.source.label), \(generated.tone.label) tone"
            )
    }

    private var provenanceText: String {
        let time = generated.generatedAt.formatted(.dateTime.hour().minute())
        return "\(generated.source.label) · \(generated.tone.label) · \(time)"
    }

    private var copyButton: some View {
        Button {
            guard let copyText else { return }
            UIPasteboard.general.string = copyText
            didCopy = true
            Task {
                try? await Task.sleep(nanoseconds: 2_000_000_000)
                didCopy = false
            }
        } label: {
            Label(didCopy ? "Copied" : "Copy", systemImage: didCopy ? "checkmark" : "doc.on.doc")
                .font(.caption.weight(.semibold))
                .foregroundStyle(.secondary)
                .frame(minWidth: 44, minHeight: 44, alignment: .trailing)
                .contentShape(Rectangle())
        }
        .buttonStyle(PressScaleButtonStyle())
        .disabled(copyText == nil)
        .copyConfirmationHaptic(trigger: didCopy)
        .accessibilityIdentifier("copyDailySummaryButton")
    }
}

/// A bulleted section, rendered as nothing at all when empty — a header with blank space under it
/// reads as a bug, and a quiet day legitimately produces an empty list.
struct DailySummaryBulletSection: View {
    let title: String
    let systemImage: String
    let items: [String]

    var body: some View {
        if !items.isEmpty {
            VStack(alignment: .leading, spacing: 8) {
                Label(title, systemImage: systemImage)
                    .sectionLabel()
                    .foregroundStyle(.secondary)
                ForEach(Array(items.enumerated()), id: \.offset) { _, item in
                    HStack(alignment: .firstTextBaseline, spacing: 8) {
                        Image(systemName: "circle.fill")
                            .font(.system(size: 4))
                            .foregroundStyle(.tint)
                        Text(item)
                            .font(.subheadline)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }
}

struct DailySummaryParagraphSection: View {
    let title: String
    let systemImage: String
    /// Named `text`, not `body` — `body` is `View`'s own requirement and collides.
    let text: String

    var body: some View {
        if !text.isEmpty {
            VStack(alignment: .leading, spacing: 8) {
                Label(title, systemImage: systemImage)
                    .sectionLabel()
                    .foregroundStyle(.secondary)
                Text(text)
                    .font(.subheadline)
                    .fixedSize(horizontal: false, vertical: true)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }
}

/// The failed state — the real message, not a generic apology, because the two failure sources
/// (Firestore read vs generator) need different fixes from the user.
struct DailySummaryFailureCard: View {
    let message: String

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Label("Couldn't generate", systemImage: "exclamationmark.triangle.fill")
                .font(.subheadline.weight(.bold))
                .foregroundStyle(.tint)
            Text(message)
                .font(.footnote)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .bentoCard()
    }
}

/// The §3 press-scale primitive for the card's non-chip buttons. Raw opacity filters are
/// prohibited, so the press state is a scale.
struct PressScaleButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .scaleEffect(configuration.isPressed ? 0.97 : 1)
            .animation(
                .spring(response: 0.35, dampingFraction: 0.8, blendDuration: 0),
                value: configuration.isPressed
            )
    }
}

extension View {
    /// Tactile confirmation on copy (§3). `.sensoryFeedback` is iOS 17+ and the deployment target
    /// is 16.0, so it is gated — the same §7 precedent as `expandCollapseHaptic`.
    @ViewBuilder
    func copyConfirmationHaptic(trigger: Bool) -> some View {
        if #available(iOS 17.0, *) {
            self.sensoryFeedback(.success, trigger: trigger) { _, _ in
                AppFeedback.hapticsEnabled()
            }
        } else {
            self
        }
    }
}

#Preview("Light") {
    ScrollView {
        DailySummaryResultCard(
            generated: GeneratedDailySummary(
                content: DailySummaryContent(
                    headline: "2 finished today — that momentum is real.",
                    dopamineWins: ["Shipped: the capture fix.", "Shipped: the summary card."],
                    journalReflections: "2 entries written today, energy running high.",
                    focusStaminaInsight: "48 minutes of focused work today.",
                    gentleTomorrowKickstart: ["Start with the prompt draft."]
                ),
                tone: .energizing, generatedAt: .now, source: .localSynthesis
            ),
            copyText: "…"
        )
        .padding(16)
    }
    .preferredColorScheme(.light)
}

#Preview("Dark — failed") {
    ScrollView {
        DailySummaryFailureCard(message: "Could not read today's tasks.")
            .padding(16)
    }
    .preferredColorScheme(.dark)
}
