#!/usr/bin/env python3
"""LifeOS Capture, rebuilt against the Firebase Cloud Function.

Far simpler than the direct-REST version: the function owns the document id, the timestamp, the
Storage upload and the download URL, so the Shortcut is one menu and one POST.
"""
import plistlib

PH = "￼"
ENDPOINT = "https://capture-dg5rypfbaq-uc.a.run.app"

U = {
    "key": "169396F7-31E6-4F4C-B11A-4719E91C4FF0",
    "asknote": "F2FF1EF8-BA06-4CDB-A643-DB681CCB010E",
    "kindnote": "83B135B4-C73A-453B-A98D-33E0DACE9E71",
    "asktask": "52BF5374-C0BA-4749-9B01-47E15429735C",
    "kindtask": "52C6896F-2D94-4BFA-B23F-645A4BC30013",
    "asklink": "CCC149F2-D752-45BA-8627-F4BA22B544EF",
    "kindlink": "7E59D94E-3ACF-4B21-9745-11F40AD25342",
    "photo": "402B57D3-CF5A-4C68-AF32-125C582ACC1B",
    "photob64": "115EB36B-6757-432A-B1AC-00840E985494",
    "photomedia": "3CE9DCC6-68B2-4104-9663-CE345D877313",
    "kindphoto": "55FF136A-8FEF-4D03-973A-53987105DDA1",
    "voice": "7BC9C897-2991-4266-978D-BE1CC07CCF78",
    "voiceb64": "A091286D-C1BD-466A-89AD-DFCCD1A8920A",
    "voicemedia": "EC56DC17-641E-4A22-BDD9-769D6EB0DA23",
    "kindvoice": "C63323DC-BDC0-4D24-9B99-2A6C614A97AD",
    "emptymedia": "EC66DA09-EDAC-4326-99CF-429B947B1FE9",
    "escquote": "64DE93C1-C7FB-46D2-A107-A5F250830837",
    "escnl": "DBA60AAD-B208-4964-AA7F-351734CE9579",
    "body": "F8BE231D-A2E2-44D0-87DA-9B095F447A0E",
    "post": "5193293C-C64F-4993-9B24-C3716B01AD9F",
    "emptycontent": "D05211B4-71DB-4584-A2F6-96CDE8F40D63",
}
G_MENU = "3283A715-204A-44DD-8943-10960956F33A"


def token_string(text, attachments):
    positions = [i for i, ch in enumerate(text) if ch == PH]
    assert len(positions) == len(attachments), (len(positions), len(attachments), text)
    return {
        "Value": {
            "attachmentsByRange": {
                "{%d, 1}" % pos: att for pos, att in zip(positions, attachments)
            },
            "string": text,
        },
        "WFSerializationType": "WFTextTokenString",
    }


def var(name):
    return {"Type": "Variable", "VariableName": name}


def out(uuid, name):
    return {"Type": "ActionOutput", "OutputUUID": uuid, "OutputName": name}


def attachment(att):
    return {"Value": att, "WFSerializationType": "WFTextTokenAttachment"}


def action(identifier, params):
    return {"WFWorkflowActionIdentifier": identifier, "WFWorkflowActionParameters": params}


def comment(text):
    return action("is.workflow.actions.comment", {"WFCommentActionText": text})


def text_action(uuid, text):
    """`text` may be a plain string or an already-built token string."""
    return action("is.workflow.actions.gettext", {"UUID": uuid, "WFTextActionText": text})


def set_var(name, att):
    return action("is.workflow.actions.setvariable",
                  {"WFVariableName": name, "WFInput": attachment(att)})


actions = []

actions.append(comment(
    "LifeOS Capture — a note, task, link, photo or voice memo, straight into the ADHD LifeOS "
    "inbox. Posts to the app's own Firebase capture function."
))
actions.append(comment(
    "Shortcuts generated by Shortcuts Playground.\n"
    "Prompt: rebuild the LifeOS capture shortcut against the Firebase Cloud Function that "
    "replaced the retired AWS endpoint."
))

actions.append(comment(
    "SETUP — do this once.\n"
    "• Paste your CAPTURE_SECRET into the Text action directly below.\n"
    "• If deploy printed a different function URL, update it in the Get Contents of URL action "
    "at the bottom.\n"
    "• Nothing else needs editing."
))
actions.append(text_action(U["key"], "PASTE_YOUR_CAPTURE_SECRET_HERE"))
actions.append(set_var("CaptureKey", out(U["key"], "Text")))

actions.append(comment(
    "Media starts as the JSON literal null, so a note, task or link posts no file — the function "
    "rejects media on those kinds. Photo and Voice overwrite it with a real media object."
))
actions.append(text_action(U["emptymedia"], "null"))
actions.append(set_var("Media", out(U["emptymedia"], "Text")))

actions.append(comment(
    "WHAT ARE YOU CAPTURING?\n"
    "- Each branch sets Kind, and either Content or Media\n"
    "- Photo and Voice base64-encode the file into Media\n"
    "- Every branch shares the single upload at the bottom"
))
actions.append(action("is.workflow.actions.choosefrommenu", {
    "GroupingIdentifier": G_MENU,
    "WFControlFlowMode": 0,
    "WFMenuPrompt": "Capture",
    "WFMenuItems": ["Quick Note", "Task", "Link", "Photo", "Voice"],
}))

# ---- text branches -------------------------------------------------------
for label, prompt, kind, ask_uuid, kind_uuid, input_type in [
    ("Quick Note", "What's on your mind?", "note", U["asknote"], U["kindnote"], "Text"),
    ("Task", "What needs doing?", "task", U["asktask"], U["kindtask"], "Text"),
    ("Link", "Paste the link", "link", U["asklink"], U["kindlink"], "URL"),
]:
    actions.append(action("is.workflow.actions.choosefrommenu", {
        "GroupingIdentifier": G_MENU, "WFControlFlowMode": 1, "WFMenuItemTitle": label,
    }))
    actions.append(action("is.workflow.actions.ask", {
        "UUID": ask_uuid, "WFAskActionPrompt": prompt, "WFInputType": input_type,
    }))
    actions.append(set_var("Content", out(ask_uuid, "Provided Input")))
    actions.append(text_action(kind_uuid, kind))
    actions.append(set_var("Kind", out(kind_uuid, "Text")))

# ---- photo ---------------------------------------------------------------
actions.append(action("is.workflow.actions.choosefrommenu", {
    "GroupingIdentifier": G_MENU, "WFControlFlowMode": 1, "WFMenuItemTitle": "Photo",
}))
actions.append(action("is.workflow.actions.takephoto", {
    "UUID": U["photo"], "WFCameraCaptureShowPreview": True,
}))
actions.append(action("is.workflow.actions.base64encode", {
    "UUID": U["photob64"],
    "WFInput": attachment(out(U["photo"], "Photos")),
    "WFEncodeMode": "Encode",
}))
actions.append(text_action(U["photomedia"], token_string(
    '{"data":"' + PH + '","contentType":"image/jpeg"}',
    [out(U["photob64"], "Base64 Encoded")],
)))
actions.append(set_var("Media", out(U["photomedia"], "Text")))
actions.append(text_action(U["kindphoto"], "photo"))
actions.append(set_var("Kind", out(U["kindphoto"], "Text")))

# ---- voice ---------------------------------------------------------------
actions.append(action("is.workflow.actions.choosefrommenu", {
    "GroupingIdentifier": G_MENU, "WFControlFlowMode": 1, "WFMenuItemTitle": "Voice",
}))
actions.append(action("is.workflow.actions.recordaudio", {
    "UUID": U["voice"], "WFRecordingStart": "On Tap", "WFRecordingEnd": "On Tap",
}))
actions.append(action("is.workflow.actions.base64encode", {
    "UUID": U["voiceb64"],
    "WFInput": attachment(out(U["voice"], "Recording")),
    "WFEncodeMode": "Encode",
}))
actions.append(text_action(U["voicemedia"], token_string(
    '{"data":"' + PH + '","contentType":"audio/m4a"}',
    [out(U["voiceb64"], "Base64 Encoded")],
)))
actions.append(set_var("Media", out(U["voicemedia"], "Text")))
actions.append(text_action(U["kindvoice"], "voice"))
actions.append(set_var("Kind", out(U["kindvoice"], "Text")))

actions.append(action("is.workflow.actions.choosefrommenu", {
    "GroupingIdentifier": G_MENU, "WFControlFlowMode": 2,
}))

# ---- send ----------------------------------------------------------------
actions.append(comment(
    "SEND IT.\n"
    "• The two Replace Text actions make the captured text safe inside JSON — do not remove them.\n"
    "• Media is empty for note, task and link; the function rejects media on those kinds.\n"
    "• The key travels in the X-LifeOS-Key header, never in the body."
))
actions.append(action("is.workflow.actions.text.replace", {
    "UUID": U["escquote"],
    "WFInput": token_string(PH, [var("Content")]),
    "WFReplaceTextFind": "\"",
    "WFReplaceTextReplace": "\\\"",
}))
actions.append(action("is.workflow.actions.text.replace", {
    "UUID": U["escnl"],
    "WFInput": token_string(PH, [out(U["escquote"], "Updated Text")]),
    "WFReplaceTextFind": "[\\r\\n]+",
    "WFReplaceTextReplace": " ",
    "WFReplaceTextRegularExpression": True,
}))
actions.append(text_action(U["body"], token_string(
    '{"kind":"' + PH + '","content":"' + PH + '","media":' + PH + '}',
    [var("Kind"), out(U["escnl"], "Updated Text"), var("Media")],
)))
actions.append(action("is.workflow.actions.downloadurl", {
    "UUID": U["post"],
    "WFURL": token_string(ENDPOINT, []),
    "WFHTTPMethod": "POST",
    "WFHTTPBodyType": "File",
    "WFRequestVariable": attachment(out(U["body"], "Text")),
    "WFHTTPHeaders": {
        "Value": {"WFDictionaryFieldValueItems": [
            {"WFItemType": 0,
             "WFKey": token_string("X-LifeOS-Key", []),
             "WFValue": token_string(PH, [var("CaptureKey")])},
            {"WFItemType": 0,
             "WFKey": token_string("Content-Type", []),
             "WFValue": token_string("application/json", [])},
        ]},
        "WFSerializationType": "WFDictionaryFieldValue",
    },
}))
actions.append(action("is.workflow.actions.notification", {
    "WFNotificationActionTitle": "Captured",
    "WFNotificationActionBody": token_string(
        "Sent to your LifeOS inbox as a " + PH + ".", [var("Kind")]),
    "WFNotificationActionSound": False,
}))

workflow = {
    "WFWorkflowActions": actions,
    "WFWorkflowClientVersion": "2700.0.4",
    "WFWorkflowHasOutputFallback": False,
    "WFWorkflowHasShortcutInputVariables": False,
    "WFWorkflowIcon": {
        "WFWorkflowIconGlyphNumber": 61440,
        "WFWorkflowIconStartColor": 4282601983,
    },
    "WFWorkflowImportQuestions": [],
    "WFWorkflowInputContentItemClasses": [],
    "WFWorkflowMinimumClientVersion": 900,
    "WFWorkflowMinimumClientVersionString": "900",
    "WFWorkflowName": "LifeOS Capture",
    "WFWorkflowOutputContentItemClasses": [],
    "WFWorkflowTypes": [],
}

path = "shortcuts/LifeOS Capture.xml"

with open(path, "wb") as f:
    plistlib.dump(workflow, f, fmt=plistlib.FMT_XML, sort_keys=False)
print("wrote", path, "with", len(actions), "actions")
